config/routes.rb
ParseTest::Application.routes.draw do
  resources :fornecedors

  resources :procons

  resources :atendimentos

  
  
  resources :atendimentos do
    collection {post :import}
  end

resources :procons do
    collection {post :import}
  end
 

end

app/models/atendimento.rb
class Atendimento < ActiveRecord::Base
  attr_accessible :AnoAtendimento, :CEPConsumidor, :CodigoAssunto, :CodigoProblema, :CodigoRegiao, :CodigoTipoAtendimento,:DataAtendimento, :DescricaoAssunto, :DescricaoProblema, :DescricaoTipoAtendimento, :FaixaEtariaConsumidor, :GrupoAssunto,   :GrupoProblema, :MesAtendimento, :Regiao, :SexoConsumidor, :TrimestreAtendimento, :UF
def self.import(file)
    CSV.foreach(file.path, col_sep: ';', headers: true, encoding: "iso-8859-1:UTF-8") do |row|
      Atendimento.create! :AnoAtendimento => row[0], :DataAtendimento => row[3],:CEPConsumidor => row[17], :CodigoAssunto => row[9]

      #{:AnoAtendimento => row[0], :TrimestreAtendimento => row[1]}
    end
  end
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  attr_accessible :cnpj, :descricao_cnaep_principal, :nome_fantasia, :razao_social_sindec, :tipo_fornecedor
end

app/models/procon.rb
#encoding: utf-8
class Procon < ActiveRecord::Base
  attr_accessible :DDD, :cargo, :email, :endereco, :fax, :responsavel, :telefone
def self.import(file)
    CSV.foreach(file.path, col_sep: ',', headers: true, encoding: "iso-8859-1:UTF-8") do |row|
      Procon.create! :DDD => row[7], :cargo => row[5],
      :email => row[12], :endereco => row[6], :fax => row[10], 
      :responsavel => row[4], :telefone => [row[8] ,row[9]]

      #{:AnoAtendimento => row[0], :TrimestreAtendimento => row[1]}
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/atendimentos_controller.rb
class AtendimentosController < ApplicationController
  # GET /atendimentos
  # GET /atendimentos.json
  def index
    @atendimentos = Atendimento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @atendimentos }
    end
  end

  def import
    
    Atendimento.import(params[:file])
    redirect_to atendimentos_url, notice:  "Convenios importados com sucesso"

  end

  # GET /atendimentos/1
  # GET /atendimentos/1.json
  def show
    @atendimento = Atendimento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @atendimento }
    end
  end

  # GET /atendimentos/new
  # GET /atendimentos/new.json
  def new
    @atendimento = Atendimento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @atendimento }
    end
  end

  # GET /atendimentos/1/edit
  def edit
    @atendimento = Atendimento.find(params[:id])
  end

  # POST /atendimentos
  # POST /atendimentos.json
  def create
    @atendimento = Atendimento.new(params[:atendimento])

    respond_to do |format|
      if @atendimento.save
        format.html { redirect_to @atendimento, notice: 'Atendimento was successfully created.' }
        format.json { render json: @atendimento, status: :created, location: @atendimento }
      else
        format.html { render action: "new" }
        format.json { render json: @atendimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /atendimentos/1
  # PUT /atendimentos/1.json
  def update
    @atendimento = Atendimento.find(params[:id])

    respond_to do |format|
      if @atendimento.update_attributes(params[:atendimento])
        format.html { redirect_to @atendimento, notice: 'Atendimento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @atendimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atendimentos/1
  # DELETE /atendimentos/1.json
  def destroy
    @atendimento = Atendimento.find(params[:id])
    @atendimento.destroy

    respond_to do |format|
      format.html { redirect_to atendimentos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  # GET /fornecedors
  # GET /fornecedors.json
  def index
    @fornecedors = Fornecedor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fornecedors }
    end
  end

  # GET /fornecedors/1
  # GET /fornecedors/1.json
  def show
    @fornecedor = Fornecedor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fornecedor }
    end
  end

  # GET /fornecedors/new
  # GET /fornecedors/new.json
  def new
    @fornecedor = Fornecedor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fornecedor }
    end
  end

  # GET /fornecedors/1/edit
  def edit
    @fornecedor = Fornecedor.find(params[:id])
  end

  # POST /fornecedors
  # POST /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(params[:fornecedor])

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully created.' }
        format.json { render json: @fornecedor, status: :created, location: @fornecedor }
      else
        format.html { render action: "new" }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fornecedors/1
  # PUT /fornecedors/1.json
  def update
    @fornecedor = Fornecedor.find(params[:id])

    respond_to do |format|
      if @fornecedor.update_attributes(params[:fornecedor])
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1
  # DELETE /fornecedors/1.json
  def destroy
    @fornecedor = Fornecedor.find(params[:id])
    @fornecedor.destroy

    respond_to do |format|
      format.html { redirect_to fornecedors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/procons_controller.rb
# -*- encoding : utf-8 -*-
class ProconsController < ApplicationController
  # GET /procons
  # GET /procons.json
  def index
    @procons = Procon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @procons }
    end
  end

  def import
    
    Procon.import(params[:file])
    redirect_to procons_url, notice:  "Convenios importados com sucesso"

  end

  # GET /procons/1
  # GET /procons/1.json
  def show
    @procon = Procon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @procon }
    end
  end

  # GET /procons/new
  # GET /procons/new.json
  def new
    @procon = Procon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @procon }
    end
  end

  # GET /procons/1/edit
  def edit
    @procon = Procon.find(params[:id])
  end

  # POST /procons
  # POST /procons.json
  def create
    @procon = Procon.new(params[:procon])

    respond_to do |format|
      if @procon.save
        format.html { redirect_to @procon, notice: 'Procon was successfully created.' }
        format.json { render json: @procon, status: :created, location: @procon }
      else
        format.html { render action: "new" }
        format.json { render json: @procon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /procons/1
  # PUT /procons/1.json
  def update
    @procon = Procon.find(params[:id])

    respond_to do |format|
      if @procon.update_attributes(params[:procon])
        format.html { redirect_to @procon, notice: 'Procon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @procon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procons/1
  # DELETE /procons/1.json
  def destroy
    @procon = Procon.find(params[:id])
    @procon.destroy

    respond_to do |format|
      format.html { redirect_to procons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/helpers/procons_helper.rb
module ProconsHelper
end

app/views/atendimentos/_form.html.erb
<%= form_for(@atendimento) do |f| %>
  <% if @atendimento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atendimento.errors.count, "error") %> prohibited this atendimento from being saved:</h2>

      <ul>
      <% @atendimento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :AnoAtendimento %><br />
    <%= f.number_field :AnoAtendimento %>
  </div>
  <div class="field">
    <%= f.label :TrimestreAtendimento %><br />
    <%= f.number_field :TrimestreAtendimento %>
  </div>
  <div class="field">
    <%= f.label :MesAtendimento %><br />
    <%= f.number_field :MesAtendimento %>
  </div>
  <div class="field">
    <%= f.label :DataAtendimento %><br />
    <%= f.date_select :DataAtendimento %>
  </div>
  <div class="field">
    <%= f.label :CodigoRegiao %><br />
    <%= f.number_field :CodigoRegiao %>
  </div>
  <div class="field">
    <%= f.label :Regiao %><br />
    <%= f.text_field :Regiao %>
  </div>
  <div class="field">
    <%= f.label :UF %><br />
    <%= f.text_field :UF %>
  </div>
  <div class="field">
    <%= f.label :CodigoTipoAtendimento %><br />
    <%= f.number_field :CodigoTipoAtendimento %>
  </div>
  <div class="field">
    <%= f.label :DescricaoTipoAtendimento %><br />
    <%= f.text_field :DescricaoTipoAtendimento %>
  </div>
  <div class="field">
    <%= f.label :CodigoAssunto %><br />
    <%= f.number_field :CodigoAssunto %>
  </div>
  <div class="field">
    <%= f.label :DescricaoAssunto %><br />
    <%= f.text_field :DescricaoAssunto %>
  </div>
  <div class="field">
    <%= f.label :GrupoAssunto %><br />
    <%= f.text_field :GrupoAssunto %>
  </div>
  <div class="field">
    <%= f.label :CodigoProblema %><br />
    <%= f.number_field :CodigoProblema %>
  </div>
  <div class="field">
    <%= f.label :DescricaoProblema %><br />
    <%= f.text_field :DescricaoProblema %>
  </div>
  <div class="field">
    <%= f.label :GrupoProblema %><br />
    <%= f.text_field :GrupoProblema %>
  </div>
  <div class="field">
    <%= f.label :SexoConsumidor %><br />
    <%= f.text_field :SexoConsumidor %>
  </div>
  <div class="field">
    <%= f.label :FaixaEtariaConsumidor %><br />
    <%= f.text_field :FaixaEtariaConsumidor %>
  </div>
  <div class="field">
    <%= f.label :CEPConsumidor %><br />
    <%= f.number_field :CEPConsumidor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atendimentos/edit.html.erb
<h1>Editing atendimento</h1>

<%= render 'form' %>

<%= link_to 'Show', @atendimento %> |
<%= link_to 'Back', atendimentos_path %>

app/views/atendimentos/import.html.erb
Csv importado com sucesso!

app/views/atendimentos/index.html.erb
<h1>Listing atendimentos</h1>

<table>
  <tr>
    <th>Anoatendimento</th>
    <th>Trimestreatendimento</th>
    <th>Mesatendimento</th>
    <th>Dataatendimento</th>
    <th>Codigoregiao</th>
    <th>Regiao</th>
    <th>Uf</th>
    <th>Codigotipoatendimento</th>
    <th>Descricaotipoatendimento</th>
    <th>Codigoassunto</th>
    <th>Descricaoassunto</th>
    <th>Grupoassunto</th>
    <th>Codigoproblema</th>
    <th>Descricaoproblema</th>
    <th>Grupoproblema</th>
    <th>Sexoconsumidor</th>
    <th>Faixaetariaconsumidor</th>
    <th>Cepconsumidor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @atendimentos.each do |atendimento| %>
  <tr>
    <td><%= atendimento.AnoAtendimento %></td>
    <td><%= atendimento.TrimestreAtendimento %></td>
    <td><%= atendimento.MesAtendimento %></td>
    <td><%= atendimento.DataAtendimento %></td>
    <td><%= atendimento.CodigoRegiao %></td>
    <td><%= atendimento.Regiao %></td>
    <td><%= atendimento.UF %></td>
    <td><%= atendimento.CodigoTipoAtendimento %></td>
    <td><%= atendimento.DescricaoTipoAtendimento %></td>
    <td><%= atendimento.CodigoAssunto %></td>
    <td><%= atendimento.DescricaoAssunto %></td>
    <td><%= atendimento.GrupoAssunto %></td>
    <td><%= atendimento.CodigoProblema %></td>
    <td><%= atendimento.DescricaoProblema %></td>
    <td><%= atendimento.GrupoProblema %></td>
    <td><%= atendimento.SexoConsumidor %></td>
    <td><%= atendimento.FaixaEtariaConsumidor %></td>
    <td><%= atendimento.CEPConsumidor %></td>
    <td><%= link_to 'Show', atendimento %></td>
    <td><%= link_to 'Edit', edit_atendimento_path(atendimento) %></td>
    <td><%= link_to 'Destroy', atendimento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>



<br />

<%= link_to 'New Atendimento', new_atendimento_path %>

app/views/atendimentos/new.html.erb
<h1>New atendimento</h1>

<h2>Import Products</h2>

<%= form_tag import_atendimentos_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/atendimentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Anoatendimento:</b>
  <%= @atendimento.AnoAtendimento %>
</p>

<p>
  <b>Trimestreatendimento:</b>
  <%= @atendimento.TrimestreAtendimento %>
</p>

<p>
  <b>Mesatendimento:</b>
  <%= @atendimento.MesAtendimento %>
</p>

<p>
  <b>Dataatendimento:</b>
  <%= @atendimento.DataAtendimento %>
</p>

<p>
  <b>Codigoregiao:</b>
  <%= @atendimento.CodigoRegiao %>
</p>

<p>
  <b>Regiao:</b>
  <%= @atendimento.Regiao %>
</p>

<p>
  <b>Uf:</b>
  <%= @atendimento.UF %>
</p>

<p>
  <b>Codigotipoatendimento:</b>
  <%= @atendimento.CodigoTipoAtendimento %>
</p>

<p>
  <b>Descricaotipoatendimento:</b>
  <%= @atendimento.DescricaoTipoAtendimento %>
</p>

<p>
  <b>Codigoassunto:</b>
  <%= @atendimento.CodigoAssunto %>
</p>

<p>
  <b>Descricaoassunto:</b>
  <%= @atendimento.DescricaoAssunto %>
</p>

<p>
  <b>Grupoassunto:</b>
  <%= @atendimento.GrupoAssunto %>
</p>

<p>
  <b>Codigoproblema:</b>
  <%= @atendimento.CodigoProblema %>
</p>

<p>
  <b>Descricaoproblema:</b>
  <%= @atendimento.DescricaoProblema %>
</p>

<p>
  <b>Grupoproblema:</b>
  <%= @atendimento.GrupoProblema %>
</p>

<p>
  <b>Sexoconsumidor:</b>
  <%= @atendimento.SexoConsumidor %>
</p>

<p>
  <b>Faixaetariaconsumidor:</b>
  <%= @atendimento.FaixaEtariaConsumidor %>
</p>

<p>
  <b>Cepconsumidor:</b>
  <%= @atendimento.CEPConsumidor %>
</p>


<%= link_to 'Edit', edit_atendimento_path(@atendimento) %> |
<%= link_to 'Back', atendimentos_path %>

app/views/fornecedors/_form.html.erb
<%= form_for(@fornecedor) do |f| %>
  <% if @fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
      <% @fornecedor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_fornecedor %><br />
    <%= f.number_field :tipo_fornecedor %>
  </div>
  <div class="field">
    <%= f.label :razao_social_sindec %><br />
    <%= f.text_field :razao_social_sindec %>
  </div>
  <div class="field">
    <%= f.label :nome_fantasia %><br />
    <%= f.text_field :nome_fantasia %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :descricao_cnaep_principal %><br />
    <%= f.text_field :descricao_cnaep_principal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fornecedors/edit.html.erb
<h1>Editing fornecedor</h1>

<%= render 'form' %>

<%= link_to 'Show', @fornecedor %> |
<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/index.html.erb
<h1>Listing fornecedors</h1>

<table>
  <tr>
    <th>Tipo fornecedor</th>
    <th>Razao social sindec</th>
    <th>Nome fantasia</th>
    <th>Cnpj</th>
    <th>Descricao cnaep principal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fornecedors.each do |fornecedor| %>
  <tr>
    <td><%= fornecedor.tipo_fornecedor %></td>
    <td><%= fornecedor.razao_social_sindec %></td>
    <td><%= fornecedor.nome_fantasia %></td>
    <td><%= fornecedor.cnpj %></td>
    <td><%= fornecedor.descricao_cnaep_principal %></td>
    <td><%= link_to 'Show', fornecedor %></td>
    <td><%= link_to 'Edit', edit_fornecedor_path(fornecedor) %></td>
    <td><%= link_to 'Destroy', fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fornecedor', new_fornecedor_path %>

app/views/fornecedors/new.html.erb
<h1>New fornecedor</h1>

<%= render 'form' %>

<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo fornecedor:</b>
  <%= @fornecedor.tipo_fornecedor %>
</p>

<p>
  <b>Razao social sindec:</b>
  <%= @fornecedor.razao_social_sindec %>
</p>

<p>
  <b>Nome fantasia:</b>
  <%= @fornecedor.nome_fantasia %>
</p>

<p>
  <b>Cnpj:</b>
  <%= @fornecedor.cnpj %>
</p>

<p>
  <b>Descricao cnaep principal:</b>
  <%= @fornecedor.descricao_cnaep_principal %>
</p>


<%= link_to 'Edit', edit_fornecedor_path(@fornecedor) %> |
<%= link_to 'Back', fornecedors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParseTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/procons/_form.html.erb
<%= form_for(@procon) do |f| %>
  <% if @procon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@procon.errors.count, "error") %> prohibited this procon from being saved:</h2>

      <ul>
      <% @procon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :responsavel %><br />
    <%= f.text_field :responsavel %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br />
    <%= f.text_field :cargo %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :DDD %><br />
    <%= f.number_field :DDD %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/procons/edit.html.erb
<h1>Editing procon</h1>

<%= render 'form' %>

<%= link_to 'Show', @procon %> |
<%= link_to 'Back', procons_path %>

app/views/procons/import.html.erb
importado com sucesso!

app/views/procons/index.html.erb
<h1>Listing procons</h1>

<table>
  <tr>
    <th>Responsavel</th>
    <th>Cargo</th>
    <th>Endereco</th>
    <th>Ddd</th>
    <th>Telefone</th>
    <th>Fax</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @procons.each do |procon| %>
  <tr>
    <td><%= procon.responsavel %></td>
    <td><%= procon.cargo %></td>
    <td><%= procon.endereco %></td>
    <td><%= procon.DDD %></td>
    <td><%= procon.telefone %></td>
    <td><%= procon.fax %></td>
    <td><%= procon.email %></td>
    <td><%= link_to 'Show', procon %></td>
    <td><%= link_to 'Edit', edit_procon_path(procon) %></td>
    <td><%= link_to 'Destroy', procon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Procon', new_procon_path %>

app/views/procons/new.html.erb
<h1>New procon</h1>

<h2>Import Products</h2>

<%= form_tag import_procons_path, multipart: true do %>
  <%= file_field_tag :file, :multiple =>true %>
  <%= submit_tag "Import" %>
<% end %>

app/views/procons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Responsavel:</b>
  <%= @procon.responsavel %>
</p>

<p>
  <b>Cargo:</b>
  <%= @procon.cargo %>
</p>

<p>
  <b>Endereco:</b>
  <%= @procon.endereco %>
</p>

<p>
  <b>Ddd:</b>
  <%= @procon.DDD %>
</p>

<p>
  <b>Telefone:</b>
  <%= @procon.telefone %>
</p>

<p>
  <b>Fax:</b>
  <%= @procon.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @procon.email %>
</p>


<%= link_to 'Edit', edit_procon_path(@procon) %> |
<%= link_to 'Back', procons_path %>